//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDialer.Ad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartDialer.Ad.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;adMob Page&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; user-scaleable=no; initial-scale=1.0&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;AdMob&quot; onclick=&quot;top.location.href=&apos;{url}&apos;;&quot; style=&quot;cursor: pointer;width:320px;padding:1 1 1 1;position:absolute;top:0px;left:0px;height:55px&quot; &gt;
        ///        &lt;div style=&quot;float:left&quot;&gt;&lt;img src=&quot;http://mm.admob.com/static/pre/img/generic.png&quot; alt=&quot;generic icon&quot; /&gt;&lt;/div&gt;
        ///        &lt;div style=&quot;float:right; margin-top:3px;&quot;&gt;&lt;img src=&quot;http://mm.admob.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdPageTemplate {
            get {
                return ResourceManager.GetString("AdPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;script language=&quot;JavaScript&quot; type=&quot;text/JavaScript&quot;&gt;
        ///		function printUA() {
        ///			window.external.notify(navigator.userAgent);
        ///		}
        ///	&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body onload=&quot;printUA();&quot;&gt;&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string GetUserAgentScript {
            get {
                return ResourceManager.GetString("GetUserAgentScript", resourceCulture);
            }
        }
    }
}
